# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 909d361e3e286be05cfd4bb87e3cf6805058b8a86e97b2d6a4bff8ff282ef6d9d6838e49331f9a280bce685a1afbe9831a48f8dec1b9fdf0b5fe45d8e1c874c8

test:
  secret_key_base: 41305f125e66672cebd116a3a3cd5dcce6cad7373c0f31477ff65f9512d57173f0a859ca66dda5bbed6bcbf92674f62f06e83553240f6103de3edfeab37aa943

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
