# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 927ae6e4e7728d58c8084b3c5908e134e51bfecee3c8ef0bb40fb54ae1254acb9eb661968594f16865f490ee64af2f07cb4895a846a36ee178f3ff11c6cf9945

test:
  secret_key_base: bbfce67ad2b7cf22a2fbfec75d05ed88c03a5fbc259cda8272a8f43ec475c25fb81b145a1ddb83fbf5a9683798032c584ba22860a7a04b4a1afc2d07b883b1c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
